version: 2.1

parameters:
  message:
    type: string
    default: "Successfuly"

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run basic tests
          command: npm run test
          
      - run:
          name: Build the application
          command: npm run build
      
      - run:
          name: Install pre-requisites
          command: |
            sudo apt update && sudo apt install -y awscli
            
  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      
      - run:
          name: Deploying
          command: echo "Deployed << pipeline.parameters.message >>! :D"            

    
     
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - frontend-prod
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - frontend-prod


