version: 2
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.8
jobs:
  build-deploy-frontend:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run basic tests
          command: npm run test
          
      - run:
          name: Build the application
          command: npm run build
      
      - run:
          name: Install pre-requisites
          command: |
            sudo apt update && sudo apt install -y awscli
            
      - run:
          name: Send to AWS S3
          command: |
              case $CIRCLE_BRANCH in
              "frontend-prod") 
                aws s3 sync src/public/ s3://lolisslayers/ 
              ;;
              "frontend-dev") 
                aws s3 sync src/public/ s3://lolisslayers-dev/ 
              ;;
              esac 
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-deploy-frontend:
          filters:
            branches:
              only:
                - frontend-prod
                - frontend-dev
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - backend-prod
                - backend-dev
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          filters:
            branches:
              only:
                - backend-prod
                - backend-dev
          aws-region: ${AWS_DEFAULT_REGION}
          family: "${AWS_RESOURCE_NAME_PREFIX}"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX},tag=${CIRCLE_SHA1}"

