version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
            - node_modules
            - src
            - build
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          name: Get all pre-requisites
          command: |
            ls -lha &&
            apk add --no-cache \
            py-pip
            pip install \
            awscli
      - run:
          name: Send to AWS S3
          command: |
              case $CIRCLE_BRANCH in
              "master") 
                aws s3 sync src/public/ s3://lolisslayers/ 
              ;;
              "dev") 
                aws s3 sync src/public/ s3://lolisslayers-dev/ 
              ;;
              esac
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
     
